services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rails_todo_development
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b '0.0.0.0'"
    volumes:
      - .:/rails-app
      - bundle_data:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/rails_todo_development
      RAILS_ENV: development

  test:
    build: .
    volumes:
      - .:/rails-app
      - bundle_data:/usr/local/bundle
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/rails_todo_test
      RAILS_ENV: test

volumes:
  postgres_data:
  bundle_data:

