default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: postgres
  password: password

development:
  <<: *default
  database: rails_todo_development

test:
  <<: *default
  database: rails_todo_test

production:
  <<: *default
  database: rails_todo_production
  username: rails_todo
  password: <%= ENV["RAILS_TODO_DATABASE_PASSWORD"] %>
